[build]
builder = "nixpacks"

[deploy]
startCommand = "./pocketbase serve --http=0.0.0.0:8080"

[environment]
NIXPACKS_BUILD_COMMAND = "curl -L https://github.com/pocketbase/pocketbase/releases/download/v0.21.1/pocketbase_0.21.1_linux_amd64.zip -o pocketbase.zip && unzip pocketbase.zip && chmod +x pocketbase"